[project]
name = "holberton-codewars-discord-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sebastion Price", email = "sebastionprice@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "requests>=2.34.2",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
