[project]
name = "duckbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sebastion Price", email = "sebastionprice@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "pytz>=2026.3.post1",
    "requests>=2.34.2",
]

[project.scripts]
duckbot = "duckbot:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
